# Permalinks
permalink:           pretty

# Setup
title:               Lliana Shi
tagline:             A Forward Propagating Data Science Blog
url:                 http://llianashi.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lliana Shi
  url:               https://www.linkedin.com/in/shi-heping-3b453826/
  email:             lliana.shi@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/llianashi

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
